POST http://127.0.0.1:3000/auth/register
Content-Type: application/json

{
    "name": "prueba1",
    "email":"admin@gmail.com",
    "password": "123456"
}


### Login sin conexion a la bdd
POST http://127.0.0.1:3000/auth/login
Content-Type: application/json

{
    "name":"prueba2",
    "email":"eo@gmail.com",
    "password": "123456"
}

### users
GET http://127.0.0.1:3000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MzE2NDk4MDUsImV4cCI6MTczMTY0OTg2NX0.j4XJoqWGAP9NXlS4-DB1i1zM7nTBtJBB4VTlcfqsRpI